// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOGab2OEK_dKNorebkEm0_sTXPGyW0zE',
    appId: '1:67036393081:web:454283889e9d43fb4f2ea8',
    messagingSenderId: '67036393081',
    projectId: 'chatprovider-4d62a',
    authDomain: 'chatprovider-4d62a.firebaseapp.com',
    storageBucket: 'chatprovider-4d62a.appspot.com',
    measurementId: 'G-Z9G5GHWEHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGxk2xnj_W9a2AvG_RP_qf7bsNeW87yyA',
    appId: '1:67036393081:android:848377755053e59b4f2ea8',
    messagingSenderId: '67036393081',
    projectId: 'chatprovider-4d62a',
    storageBucket: 'chatprovider-4d62a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqw8AhJ2lwOAFVfytgc1khMyg3TG2yQWs',
    appId: '1:67036393081:ios:6849a25e112825cf4f2ea8',
    messagingSenderId: '67036393081',
    projectId: 'chatprovider-4d62a',
    storageBucket: 'chatprovider-4d62a.appspot.com',
    iosClientId: '67036393081-22g5vrvfvdc8i4685nfk3ffnhbqce04e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqw8AhJ2lwOAFVfytgc1khMyg3TG2yQWs',
    appId: '1:67036393081:ios:6849a25e112825cf4f2ea8',
    messagingSenderId: '67036393081',
    projectId: 'chatprovider-4d62a',
    storageBucket: 'chatprovider-4d62a.appspot.com',
    iosClientId: '67036393081-22g5vrvfvdc8i4685nfk3ffnhbqce04e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatPortfolio',
  );
}
